server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080

spring:
  application:
    name: UWBike
  datasource:
    password: ${DBPASSWORD:SuaSenhaSuperForte123!}
    url: ${DBURL:jdbc:postgresql://uwbike-sql.postgres.database.azure.com:5432/uwbike-banco}
    username: ${DBUSER:uwbike}
    driver-class-name: ${DBDRIVER:org.postgresql.Driver}
  jpa:

    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DBDIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
logging:
  level:
    org.flywaydb: off